version: '3'

services:
  main:
    image: quay.io/frrouting/frr:8.5.3
    hostname: main
    privileged: true
    volumes: 
      - ./vol/frr/main:/etc/frr:rw
    networks: 
      main-start: 
        ipv4_address: 172.18.0.2
      main-end: 
        ipv4_address: 172.18.1.2 
  top:
    image: quay.io/frrouting/frr:8.5.3
    hostname: top
    privileged: true
    volumes: 
      - ./vol/frr/top:/etc/frr:rw
    networks: 
      top-start: 
        ipv4_address: 172.18.2.2
      top-end: 
        ipv4_address: 172.18.3.2 
  bottom:
    image: quay.io/frrouting/frr:8.5.3
    hostname: bottom 
    privileged: true
    user: 0:0
    volumes: 
      - ./vol/frr/bottom:/etc/frr:rw
    networks: 
      bottom-start: 
        ipv4_address: 172.18.4.2
      bottom-end: 
        ipv4_address: 172.18.5.2 
  start:
    image: quay.io/frrouting/frr:8.5.3
    hostname: start
    privileged: true
    volumes: 
      - ./vol/frr/start:/etc/frr:rw
    networks: 
      main-start: 
        ipv4_address: 172.18.0.3
      top-start: 
        ipv4_address: 172.18.2.3 
      bottom-start: 
        ipv4_address: 172.18.4.3 
      odl-pcep:
        ipv4_address: 172.20.0.3
  end: 
    image: quay.io/frrouting/frr:8.5.3
    hostname: end
    privileged: true
    volumes: 
      - ./vol/frr/end:/etc/frr:rw
    networks: 
      main-end: 
        ipv4_address: 172.18.1.3
      top-end: 
        ipv4_address: 172.18.3.3 
      bottom-end: 
        ipv4_address: 172.18.5.3
      odl-pcep:
        ipv4_address: 172.20.0.4
  odl:
    image: opendaylight/odl
    entrypoint: /entrypoint.sh
    stdin_open: true
    volumes:
      - ./vol/odl/entrypoint.sh:/entrypoint.sh:ro
    networks:
      odl-pcep:
        ipv4_address: 172.20.0.2
networks:
  main-start:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/29
          gateway: 172.18.0.1
    driver_opts:
      com.docker.network.bridge.name: br_main_start
  top-start:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.2.0/29
          gateway: 172.18.2.1
    driver_opts:
      com.docker.network.bridge.name: br_top_start
  bottom-start:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.4.0/29
          gateway: 172.18.4.1
    driver_opts:
      com.docker.network.bridge.name: br_bottom_start
  main-end:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.1.0/29
          gateway: 172.18.1.1
    driver_opts:
      com.docker.network.bridge.name: br_main_end
  top-end:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.3.0/29
          gateway: 172.18.3.1
    driver_opts:
      com.docker.network.bridge.name: br_top_end
  bottom-end:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.5.0/29
          gateway: 172.18.5.1
    driver_opts:
      com.docker.network.bridge.name: br_bottom_end
  odl-pcep:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/29
          gateway: 172.20.0.1
    driver_opts:
      com.docker.networks.bridge.name: br_odl_pcep
